# -*- coding: utf-8 -*-
"""EjerciciosDNGA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKbt2SJ8j_e-yUSSYnhovQiV7iiZ55Vv
"""

from google.colab import files

import pandas as pd
import io
import numpy as np

uploaded = files.upload()

uploaded

dataframe = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Inventario.csv'].decode('latin-1')))

dataframe

dataframe.count()

dataframe.sum()

dataframe.cumsum()

dataframe['Cantidad'].value_counts()