# -*- coding: utf-8 -*-
"""EjerciciosEOHR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIK9gRNYAee3aG63s9BtdciLqs_wnx5W
"""

from google.colab import files

import pandas as pd
import io
import numpy as np

uploaded = files.upload()

dataframe = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Inventario.csv'].decode('latin-1')))

dataframe

dataframe.min()

dataframe.max()

dataframe['Precio Unitario'].mean()

dataframe['Cantidad'].var()

dataframe['Cantidad'].std()