# -*- coding: utf-8 -*-
"""Evidencia2_Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cz4O6nnCkw_FYt6wAhatGGEfl24rFSUx
"""

from google.colab import files

import pandas as pd
import io
import numpy as np

uploaded = files.upload()

uploaded

data = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Inventario.csv'].decode('latin-1')))

serie = data[['Producto', 'Cantidad']]

print(serie)

"""Ejercicios"""

serie.count()

serie.sum()

serie.cumsum()

serie.value_counts()

serie.min()

serie.max()

serie.mean()

serie.var()

serie.std()

serie.describe()