# -*- coding: utf-8 -*-
"""Evidencia2 - Ventas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeTLQzOPVJxI_LWJlNUeFEqnOinGseUJ
"""

from google.colab import files

import pandas as pd
import io

uploaded = files.upload()

uploaded

dataframe = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Ventas.csv'].decode('latin-1')))

dataframe