# -*- coding: utf-8 -*-
"""Evidencia2 - Ingredientes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1og4uKSJ1Tmr_mSx6geX_8yYslU-atsbF
"""

from google.colab import files

import pandas as pd
import io
import numpy as np

uploaded = files.upload()

uploaded

"""Dataframe

"""

dataframe = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Inventario (2).csv'].decode('latin-1')))

dataframe

"""Ejercicios"""

dataframe.info()

dataframe.size

dataframe.index

dataframe.dtypes

dataframe.count()

dataframe.sum()

dataframe.cumsum()

dataframe['Cantidad'].value_counts()

dataframe.min()

dataframe.max()

dataframe['Precio Unitario'].mean()

dataframe['Cantidad'].var()

dataframe['Cantidad'].std()

dataframe.describe()

dataframe.shape

dataframe.columns

dataframe.head(5)

dataframe.tail(5)

dataframe.plot()