# -*- coding: utf-8 -*-
"""Evidencia2 - Pedidos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Q0l3NYevbVhsYTwBQAv6EH4henXRzVR
"""

from google.colab import files

import pandas as pd
import io

uploaded = files.upload()

uploaded

dataframe = pd.read_csv(io.StringIO(uploaded['Evidencia2 - Pedidos.csv'].decode('latin-1')))

dataframe